services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.07.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'Europe/Warsaw'
      WEBPASSWORD: 'ChangeMe'
    volumes:
      - /etc/docker-configs/pihole:/etc/pihole
      - /etc/docker-configs/dnsmasq.d:/etc/dnsmasq.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.entrypoints=https"
      - "traefik.http.routers.pihole.rule=Host(`pihole.local.your-domain.com`)"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true