services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.11
    container_name: homepage
    restart: unless-stopped
    volumes:
      - /etc/docker-configs/homepage:/app/config
      - /etc/docker-configs/homepage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.entrypoints=https"
      - "traefik.http.routers.homepage.rule=Host(`local.your-domain.com`)"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
    networks:
      - proxy

networks:
  proxy:
    external: true