networks:
  proxy:
    external: true
  linkwarden:
    driver: bridge

services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - ${LINKWARDEN_LOCATION}/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - linkwarden
  linkwarden:
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      - NEXTAUTH_URL=https://linkwarden.${DOMAIN}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    image: ${LINKWARDEN_IMAGE_TAG}
    volumes:
      - ${LINKWARDEN_LOCATION}/data:/data/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linkwarden.entrypoints=https"
      - "traefik.http.routers.linkwarden.rule=Host(`linkwarden.${DOMAIN}`)"
      - "traefik.http.routers.linkwarden.tls=true"
      - "traefik.http.routers.linkwarden.tls.certresolver=cloudflare"
      - "traefik.http.routers.linkwarden.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.linkwarden.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.services.linkwarden.loadbalancer.server.port=${LINKWARDEN_PORT}"
      - "traefik.docker.network=proxy"
    depends_on:
      - postgres
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - linkwarden
